"""empty message

Revision ID: af3c5c1b105b
Revises: 
Create Date: 2024-02-06 15:55:50.265447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3c5c1b105b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personnel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_equipment_personnel_id', 'personnel', ['personnel_id'], ['id'])

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vehicles_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_materials_equipment_id', 'equipment', ['equipment_id'], ['id'])
        batch_op.create_foreign_key('fk_materials_vehicles_id', 'vehicles', ['vehicles_id'], ['id'])

    with op.batch_alter_table('mine_sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materials_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_mine_sections_materials_id', 'materials', ['materials_id'], ['id'])

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personnel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_vehicles_personnel_id', 'personnel', ['personnel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_equipment_personnel_id', type_='foreignkey')
        batch_op.drop_column('personnel_id')

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_constraint('fk_materials_equipment_id', type_='foreignkey')
        batch_op.drop_constraint('fk_materials_vehicles_id', type_='foreignkey')
        batch_op.drop_column('equipment_id')
        batch_op.drop_column('vehicles_id')

    with op.batch_alter_table('mine_sections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mine_sections_materials_id', type_='foreignkey')
        batch_op.drop_column('materials_id')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vehicles_personnel_id', type_='foreignkey')
        batch_op.drop_column('personnel_id')
    # ### end Alembic commands ###