"""Add latitude and longitude to mine_sections

Revision ID: cab65bf7742f
Revises: 2caf2321d6a3
Create Date: 2024-02-10 02:42:33.329132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab65bf7742f'
down_revision = '2caf2321d6a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None, naming_convention={
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    }) as batch_op:
        batch_op.add_column(sa.Column('mine_section_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_equipment_mine_section',
            'mine_sections',
            ['mine_section_id'],
            ['id']
        )

    with op.batch_alter_table('mine_sections', schema=None) as batch_op:
        batch_op.drop_column('personnel_id')
        batch_op.drop_column('vehicle_id')
        batch_op.drop_column('equipment_id')

    with op.batch_alter_table('personnel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mine_section_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_personnel_mine_section',
            'mine_sections',
            ['mine_section_id'],
            ['id']
        )

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mine_section_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_vehicles_mine_section',
            'mine_sections',
            ['mine_section_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mine_section_id')

    with op.batch_alter_table('personnel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mine_section_id')

    with op.batch_alter_table('mine_sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('vehicle_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('personnel_id', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mine_section_id')

    # ### end Alembic commands ###
